import { Job, Notification, Interview } from '../types';

export const mockJobs: Job[] = [
  // Technical Jobs
  {
    id: 1,
    title: 'Senior Full Stack Developer',
    company: { id: 1, name: 'TechCorp Solutions', logo: '🏢' },
    location: 'San Francisco, CA',
    salary_min: 120000,
    salary_max: 160000,
    employment_type_display: 'Full-time',
    is_remote: true,
    is_featured: true,
    posted_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    applications_count: 45,
    views_count: 320,
    is_active: true,
  },
  {
    id: 2,
    title: 'React.js Developer',
    company: { id: 2, name: 'WebFlow Inc', logo: '🌐' },
    location: 'New York, NY',
    salary_min: 90000,
    salary_max: 130000,
    employment_type_display: 'Full-time',
    is_remote: true,
    is_featured: false,
    posted_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    applications_count: 28,
    views_count: 210,
    is_active: true,
  },
  {
    id: 3,
    title: 'Python Backend Engineer',
    company: { id: 3, name: 'DataStream AI', logo: '🤖' },
    location: 'Remote',
    salary_min: 100000,
    salary_max: 150000,
    employment_type_display: 'Full-time',
    is_remote: true,
    is_featured: true,
    posted_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    applications_count: 62,
    views_count: 450,
    is_active: true,
  },
  {
    id: 4,
    title: 'DevOps Engineer',
    company: { id: 4, name: 'CloudInfra Ltd', logo: '☁️' },
    location: 'Austin, TX',
    salary_min: 110000,
    salary_max: 155000,
    employment_type_display: 'Full-time',
    is_remote: false,
    is_featured: false,
    posted_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    applications_count: 35,
    views_count: 180,
    is_active: true,
  },
  {
    id: 5,
    title: 'Mobile App Developer (iOS)',
    company: { id: 5, name: 'AppStudio Pro', logo: '📱' },
    location: 'Seattle, WA',
    salary_min: 95000,
    salary_max: 140000,
    employment_type_display: 'Full-time',
    is_remote: true,
    is_featured: false,
    posted_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    applications_count: 22,
    views_count: 145,
    is_active: true,
  },
  {
    id: 6,
    title: 'Data Scientist',
    company: { id: 6, name: 'Analytics Pro', logo: '📊' },
    location: 'Boston, MA',
    salary_min: 105000,
    salary_max: 160000,
    employment_type_display: 'Full-time',
    is_remote: true,
    is_featured: true,
    posted_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    applications_count: 51,
    views_count: 380,
    is_active: true,
  },
  {
    id: 7,
    title: 'QA Automation Engineer',
    company: { id: 7, name: 'QualityFirst Inc', logo: '✅' },
    location: 'Chicago, IL',
    salary_min: 80000,
    salary_max: 120000,
    employment_type_display: 'Full-time',
    is_remote: true,
    is_featured: false,
    posted_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    applications_count: 18,
    views_count: 95,
    is_active: true,
  },
  {
    id: 8,
    title: 'Cloud Architect',
    company: { id: 8, name: 'Enterprise Cloud', logo: '🏗️' },
    location: 'Denver, CO',
    salary_min: 130000,
    salary_max: 180000,
    employment_type_display: 'Full-time',
    is_remote: false,
    is_featured: false,
    posted_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    applications_count: 40,
    views_count: 290,
    is_active: true,
  },

  // Non-Technical Jobs
  {
    id: 9,
    title: 'HR Manager',
    company: { id: 9, name: 'PeopleFirst Corp', logo: '👥' },
    location: 'Los Angeles, CA',
    salary_min: 70000,
    salary_max: 100000,
    employment_type_display: 'Full-time',
    is_remote: false,
    is_featured: false,
    posted_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    applications_count: 32,
    views_count: 220,
    is_active: true,
  },
  {
    id: 10,
    title: 'Sales Executive',
    company: { id: 10, name: 'SalesForce Pro', logo: '💼' },
    location: 'Miami, FL',
    salary_min: 60000,
    salary_max: 95000,
    employment_type_display: 'Full-time',
    is_remote: true,
    is_featured: true,
    posted_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    applications_count: 55,
    views_count: 410,
    is_active: true,
  },
  {
    id: 11,
    title: 'Marketing Manager',
    company: { id: 11, name: 'BrandBoost Inc', logo: '📢' },
    location: 'Portland, OR',
    salary_min: 75000,
    salary_max: 110000,
    employment_type_display: 'Full-time',
    is_remote: true,
    is_featured: false,
    posted_at: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    applications_count: 28,
    views_count: 165,
    is_active: true,
  },
  {
    id: 12,
    title: 'Business Analyst',
    company: { id: 12, name: 'ConsultPro Ltd', logo: '📈' },
    location: 'Philadelphia, PA',
    salary_min: 65000,
    salary_max: 95000,
    employment_type_display: 'Full-time',
    is_remote: true,
    is_featured: false,
    posted_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    applications_count: 24,
    views_count: 140,
    is_active: true,
  },
  {
    id: 13,
    title: 'Content Writer',
    company: { id: 13, name: 'ContentHub Media', logo: '✍️' },
    location: 'Remote',
    salary_min: 45000,
    salary_max: 70000,
    employment_type_display: 'Full-time',
    is_remote: true,
    is_featured: false,
    posted_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    applications_count: 42,
    views_count: 280,
    is_active: true,
  },
  {
    id: 14,
    title: 'Project Manager',
    company: { id: 14, name: 'ProjectFlow Solutions', logo: '📋' },
    location: 'Atlanta, GA',
    salary_min: 80000,
    salary_max: 120000,
    employment_type_display: 'Full-time',
    is_remote: false,
    is_featured: true,
    posted_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    applications_count: 38,
    views_count: 260,
    is_active: true,
  },
  {
    id: 15,
    title: 'Customer Success Manager',
    company: { id: 15, name: 'CustomerCare Plus', logo: '😊' },
    location: 'Remote',
    salary_min: 55000,
    salary_max: 85000,
    employment_type_display: 'Full-time',
    is_remote: true,
    is_featured: false,
    posted_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    applications_count: 31,
    views_count: 195,
    is_active: true,
  },
  {
    id: 16,
    title: 'Financial Analyst',
    company: { id: 16, name: 'FinanceFirst Corp', logo: '💰' },
    location: 'New York, NY',
    salary_min: 85000,
    salary_max: 130000,
    employment_type_display: 'Full-time',
    is_remote: false,
    is_featured: false,
    posted_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    applications_count: 29,
    views_count: 175,
    is_active: true,
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 1,
    title: 'Application Viewed',
    message: 'Your application for Senior Full Stack Developer has been viewed by TechCorp Solutions',
    is_read: false,
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    notification_type: 'application',
  },
  {
    id: 2,
    title: 'New Job Match',
    message: 'A new job matching your profile: React.js Developer at WebFlow Inc',
    is_read: false,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    notification_type: 'job_match',
  },
  {
    id: 3,
    title: 'Interview Scheduled',
    message: 'Your interview for Python Backend Engineer is scheduled for tomorrow at 2 PM',
    is_read: true,
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    notification_type: 'interview',
  },
];

export const mockInterviews: Interview[] = [
  {
    id: 1,
    job_category: 'Full Stack Development',
    difficulty: 'medium',
    score: 78,
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    completed: true,
    duration_minutes: 45,
  },
  {
    id: 2,
    job_category: 'Data Science',
    difficulty: 'hard',
    score: 85,
    created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    completed: true,
    duration_minutes: 60,
  },
];
